# Common Labels
labels:
  app: "project-referral"
  group: "health"

db-read-url-enabled: true

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "project-referral"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "project_schema"
    image:
      repository: "project-db"

# Container Configs
image:
  repository: "project"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/project-referral/health"
  readinessProbePath: "/project-referral/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx1024m -Xms1024m"
java-args: ""
tracer-request-logging-enabled: "false"
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/project-persister.yml"
indexer-yml-path: "file:///work-dir/health-campaign-config/egov-indexer/project-indexer.yml"

kafka-consumer-group-id: health-project
project-task-kafka-create-topic: save-project-task-topic
project-task-consumer-bulk-create-topic: save-project-task-bulk-topic
project-task-kafka-update-topic: update-project-task-topic
project-task-consumer-bulk-update-topic: update-project-task-bulk-topic
project-task-kafka-delete-topic: delete-project-task-topic
project-task-consumer-bulk-delete-topic: delete-project-task-bulk-topic
project-beneficiary-kafka-create-topic: save-project-beneficiary-topic
project-beneficiary-kafka-update-topic: update-project-beneficiary-topic
project-beneficiary-kafka-delete-topic: delete-project-beneficiary-topic
project-beneficiary-consumer-bulk-create-topic: project-beneficiary-consumer-bulk-create-topic
project-beneficiary-consumer-bulk-update-topic: project-beneficiary-consumer-bulk-update-topic
project-beneficiary-consumer-bulk-delete-topic: project-beneficiary-consumer-bulk-delete-topic
project-staff-kafka-delete-topic: delete-project-staff-topic
project-staff-kafka-create-topic: save-project-staff-topic
project-staff-kafka-update-topic: update-project-staff-topic
project-staff-consumer-bulk-delete-topic: delete-project-staff-bulk-topic
project-staff-consumer-bulk-create-topic: create-project-staff-bulk-topic
project-staff-consumer-bulk-update-topic: update-project-staff-bulk-topic
project-management-system-kafka-create-topic: save-project
project-management-system-kafka-update-topic: update-project
project-management-system-kafka-update-date-topic: update-project-date
project-staff-attendance-topic: project-staff-attendance-health-topic
project-resource-kafka-create-topic: save-project-resource-topic
project-resource-kafka-update-topic: update-project-resource-topic
project-resource-kafka-delete-topic: delete-project-resource-topic
project-resource-consumer-bulk-create-topic: save-project-resource-bulk-topic
project-resource-consumer-bulk-update-topic: update-project-resource-bulk-topic
project-resource-consumer-bulk-delete-topic: delete-project-resource-bulk-topic
project-facility-kafka-delete-topic: delete-project-facility-topic
project-facility-kafka-create-topic: save-project-facility-topic
project-facility-kafka-update-topic: update-project-facility-topic
project-facility-consumer-bulk-delete-topic: delete-project-facility-bulk-topic
project-facility-consumer-bulk-create-topic: create-project-facility-bulk-topic
project-facility-consumer-bulk-update-topic: update-project-facility-bulk-topic
project-user-action-kafka-create-topic: save-user-action-project-task-topic
project-user-action-kafka-update-topic: update-user-action-project-task-topic
project-user-action-consumer-bulk-create-topic: save-user-action-project-bulk-topic
project-user-action-consumer-bulk-update-topic: update-user-action-project-bulk-topic
project-location-capture-kafka-create-topic: save-location-capture-project-topic
project-location-capture-consumer-bulk-create-topic: save-location-capture-project-bulk-health-topic

egov-user-id-validator: "egov-user"
task-mdms-module: "HCM-TASK-QUANTITY-VALIDATION"
project-attendance-feature-enabled: "true"
project-create-cache-key: "project-create-cache-"
project-kafka-batch-size: "100"
project-task-no-resource-validation-status: "ADMINISTRATION_FAILED,BENEFICIARY_REFUSED,CLOSED_HOUSEHOLD,NOT_ADMINISTERED,BENEFICIARY_REFERRED,BENEFICIARY_INELIGIBLE,INELIGIBLE"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: {{ index .Values "kafka-consumer-group-id" | quote }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /project-referral
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: PROJECT_STAFF_IDGEN_ID_FORMAT
    value: "project.staff.id"
  - name: PROJECT_FACILITY_IDGEN_ID_FORMAT
    value: "project.facility.id"
  - name: PROJECT_TASK_IDGEN_ID_FORMAT
    value: "project.task.id"
  - name: IDGEN_PROJECT_BENEFICIARY_ID_FORMAT
    value: "project.beneficiary.id"
  - name: SPRING_REDIS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: redis-downsync-host
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-egov
  - name: EGOV_USER_CONTEXT_PATH
    value: "/user/users"
  - name: EGOV_SEARCH_USER_URL
    value: "/user/_search"
  - name: EGOV_USER_INTEGRATION_ENABLED
    value: "true"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_LOCATION_HOST
    value: ""
  - name: EGOV_LOCATION_CONTEXT_PATH
    value: "/egov-location/location/v11"
  - name: EGOV_LOCATION_ENDPOINT
    value: "/boundarys/_search"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_INTEGRATION_ENABLED
    value: "true"
  - name: EGOV_MDMS_MASTER_NAME
    value: "project_master"
  - name: EGOV_MDMS_MODULE_NAME
    value: "project"
  - name: EGOV_HOUSEHOLD_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: household
  - name: EGOV_SEARCH_HOUSEHOLD_URL
    value: "/household/v1/_search"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_SEARCH_INDIVIDUAL_URL
    value: "/individual/v1/_search"
  - name: EGOV_PRODUCT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: product
  - name: EGOV_SEARCH_PRODUCT_VARIANT_URL
    value: "/product/variant/v1/_search"
  - name: PROJECT_TASK_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-task-kafka-create-topic" | quote }}
  - name: PROJECT_TASK_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-task-consumer-bulk-create-topic" | quote }}
  - name: PROJECT_TASK_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-task-kafka-update-topic" | quote }}
  - name: PROJECT_TASK_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "project-task-consumer-bulk-update-topic" | quote }}
  - name: PROJECT_TASK_KAFKA_DELETE_TOPIC
    value: {{ index .Values "project-task-kafka-delete-topic" | quote }}
  - name: PROJECT_TASK_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "project-task-consumer-bulk-delete-topic" | quote }}
  - name: PROJECT_BENEFICIARY_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-beneficiary-kafka-create-topic" | quote }}
  - name: PROJECT_BENEFICIARY_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-beneficiary-kafka-update-topic" | quote }}
  - name: PROJECT_BENEFICIARY_KAFKA_DELETE_TOPIC
    value: {{ index .Values "project-beneficiary-kafka-delete-topic" | quote }}
  - name: PROJECT_BENEFICIARY_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-beneficiary-consumer-bulk-create-topic" | quote }}
  - name: PROJECT_BENEFICIARY_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "project-beneficiary-consumer-bulk-update-topic" | quote }}
  - name: PROJECT_BENEFICIARY_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "project-beneficiary-consumer-bulk-delete-topic" | quote }}
  - name: PROJECT_STAFF_KAFKA_DELETE_TOPIC
    value: {{ index .Values "project-staff-kafka-delete-topic" | quote }}
  - name: PROJECT_STAFF_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-staff-kafka-create-topic" | quote }}
  - name: PROJECT_STAFF_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-staff-kafka-update-topic" | quote }}
  - name: PROJECT_STAFF_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "project-staff-consumer-bulk-delete-topic" | quote }}
  - name: PROJECT_STAFF_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-staff-consumer-bulk-create-topic" | quote }}
  - name: PROJECT_STAFF_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "project-staff-consumer-bulk-update-topic" | quote }}
  - name: SEARCH_API_LIMIT
    value: "1000"
  - name: PROJECT_DOCUMENT_ID_VERIFICATION_REQUIRED
    value: "false"
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-management-system-kafka-create-topic" | quote }}
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-management-system-kafka-update-topic" | quote }}
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_UPDATE_DATE_TOPIC
    value: {{ index .Values "project-management-system-kafka-update-date-topic" | quote }}
  - name: PROJECT_STAFF_ATTENDANCE_TOPIC
    value: {{ index .Values "project-staff-attendance-topic" | quote }}
  - name: PROJECT_DEFAULT_OFFSET
    value: "0"
  - name: PROJECT_DEFAULT_LIMIT
    value: "100"
  - name: PROJECT_SEARCH_MAX_LIMIT
    value: "200"
  - name: EGOV_IDGEN_PROJECT_NUMBER_NAME
    value: "project.number"
  - name: PROJECT_RESOURCE_IDGEN_ID_FORMAT
    value: "project.resource.id"
  - name: PROJECT_RESOURCE_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-resource-kafka-create-topic" | quote }}
  - name: PROJECT_RESOURCE_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-resource-kafka-update-topic" | quote }}
  - name: PROJECT_RESOURCE_KAFKA_DELETE_TOPIC
    value: {{ index .Values "project-resource-kafka-delete-topic" | quote }}
  - name: PROJECT_RESOURCE_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-resource-consumer-bulk-create-topic" | quote }}
  - name: PROJECT_RESOURCE_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "project-resource-consumer-bulk-update-topic" | quote }}
  - name: PROJECT_RESOURCE_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "project-resource-consumer-bulk-delete-topic" | quote }}
  - name: PROJECT_FACILITY_KAFKA_DELETE_TOPIC
    value: {{ index .Values "project-facility-kafka-delete-topic" | quote }}
  - name: PROJECT_FACILITY_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-facility-kafka-create-topic" | quote }}
  - name: PROJECT_FACILITY_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-facility-kafka-update-topic" | quote }}
  - name: PROJECT_FACILITY_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "project-facility-consumer-bulk-delete-topic" | quote }}
  - name: PROJECT_FACILITY_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-facility-consumer-bulk-create-topic" | quote }}
  - name: PROJECT_FACILITY_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "project-facility-consumer-bulk-update-topic" | quote }}
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_SEARCH_FACILITY_URL
    value: "/facility/v1/_search"
  - name: PROJECT_MDMS_MODULE
    value: "HCM-PROJECT-TYPES"
  - name: EGOV_LOCATION_HIERARCHY_TYPE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: boundary-hierarchy
  - name: EGOV_LOCATION_CODE_QUERY_PARAM
    value: "code"
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: PROJECT_TASK_NO_RESOURCE_VALIDATION_STATUS
    value: {{ index .Values "project-task-no-resource-validation-status" | quote }}
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: "/boundary-service/boundary/_search"
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: boundary-hierarchy
  - name: EGOV_USER_ID_VALIDATOR
    value: {{ index .Values "egov-user-id-validator" | quote }}
  - name: EGOV_PERSISTER_BULK_PROCESSING_ENABLED
    value: "false"
  - name: PROJECT_USER_ACTION_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-user-action-kafka-create-topic" | quote }}
  - name: PROJECT_USER_ACTION_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-user-action-kafka-update-topic" | quote }}
  - name: PROJECT_USER_ACTION_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-user-action-consumer-bulk-create-topic" | quote }}
  - name: PROJECT_USER_ACTION_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "project-user-action-consumer-bulk-update-topic" | quote }}
  - name: PROJECT_LOCATION_CAPTURE_TASK_KAFKA_CREATE_TOPIC
    value: {{ index .Values "project-location-capture-kafka-create-topic" | quote }}
  - name: PROJECT_LOCATION_CAPTURE_TASK_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "project-location-capture-consumer-bulk-create-topic" | quote }}
  - name: TASK_MDMS_MODULE
    value: {{ index .Values "task-mdms-module" | quote }}
  - name: PROJECT_ATTENDANCE_FEATURE_ENABLED
    value: {{ index .Values "project-attendance-feature-enabled" | quote }}
  - name: PROJECT_CREATE_CACHE_KEY
    value: {{ index .Values "project-create-cache-key" | quote }}
  - name: PROJECT_KAFKA_BATCH_SIZE
    value: {{ index .Values "project-kafka-batch-size" | quote }}
  - name: TRACER_REQUESTLOGGINGENABLED
    value: {{ index .Values "tracer-request-logging-enabled" | quote }}