apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: central-uat-kwara-appset-business
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dashboard-analytics

  template:
    metadata:
      name: 'kwara-{{name}}'

    spec:
      project: kwara-project

      source:
        repoURL: git@github.com:HCM-KEBBI/kebbi-devops.git
        targetRevision: central-uat-build
        path: config-as-code/helm/charts/business-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../../environments/kwara-central-uat.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '*'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 100
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
