apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: argocd
  annotations:
    monitoring-stack/managed: "true"
    monitoring-stack/do-not-deploy-standalone: "This app is managed by monitoring-stack"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.1
    helm:
      values: |
        test_pod:
          enabled: false
        loki:
          enabled: true
          isDefault: true
          image:
            tag: 2.9.3
            repository: "grafana/loki"
          service:
            port: 3100
          persistence:
            enabled: true
            accessModes:
              - ReadWriteOnce
            size: 30Gi
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::703097865444:role/nmep-central-prd-loki-role    ## AWS arn for s3 role
          config:
            auth_enabled: false
            schema_config:
              configs:
                - from: 2020-10-24
                  store: boltdb-shipper
                  object_store: s3                         ## AWS s3 as storage
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h
            storage_config:
              boltdb_shipper:
                active_index_directory: /data/loki/index
                cache_location: /data/loki/index_cache
                shared_store: s3                           ## AWS s3 as storage
                cache_ttl: 24h
              aws:
                s3: ng-nmep-central-prd-loki-bucket              ## s3 region & bucket
            compactor:
              working_directory: /data/loki/boltdb-shipper-compactor
              shared_store: s3                             ## AWS s3 as storage
              retention_enabled: true
              compaction_interval: 168h                    ## compaction in hours
            table_manager:
              retention_deletes_enabled: true
              retention_period: 168h
        promtail:
          enabled: true
          config:
            logLevel: info
            serverPort: 3101
            clients:
              - url: http://loki-stack:3100/loki/api/v1/push
        grafana:
          enabled: false
          sidecar:
            datasources:
              label: ""
              labelValue: ""
              enabled: true
              maxLines: 1000
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m