namespace: playground 

# Common Labels
labels:
  app: "playground"
  group: "playground"

# Container Configs
image:
  pullPolicy: IfNotPresent  
  repository: playground 
  tag: "1.3"
replicas: "1"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

extraVolumes: |
  - name: tmp
    emptyDir: {}

extraVolumeMounts: |
  - name: tmp
    mountPath: /tmp
