# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path: environments/ng-nmep-central-prd-secrets.yaml
    kms: 'arn:aws:kms:af-south-1:703097865444:key/54a7bfd3-459d-4861-b6e0-b8de38f4b65e'