# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path: environments/ng-health-prd-secrets.yaml
    kms: 'arn:aws:kms:af-south-1:022499048165:key/446741fe-b61c-4080-8df9-b1d6fd197cb1'
