# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path: environments/kd-health-prd-secrets.yaml
    kms: 'arn:aws:kms:af-south-1:022499048165:key/cfa29b78-5c36-4cdf-8e7a-6359f3cee80a'