# Default values for egov-finance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: backbone 

# Common Labels
labels:
  app: "redis"

# Container Configs
image:
  repository: "redis"
  pullPolicy: IfNotPresent
  tag: "3.2"
replicas: "1"
httpPort: 6379

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

extraVolumes: |
  - name: tmp
    emptyDir: {}

extraVolumeMounts: |
  - name: tmp
    mountPath: /tmp
