apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ubuntu-pod-shell-binding
subjects:
  - kind: Group
    name: ubuntu-shell-users      
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ubuntu-pod-shell
  apiGroup: rbac.authorization.k8s.io