apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: egov-project
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:HCM-NIGERIA-NMEP/nmep-devops.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding