# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path: environments/ng-health-uat-secrets.yaml
    kms: 'arn:aws:kms:af-south-1:022499048165:key/0dca14ee-35cd-4ca6-b2e7-f5577d345f03'
  - path: environments/ng-central-uat.yaml
    kms: 'arn:aws:kms:af-south-1:022499048165:key/731868a6-306f-4e37-bc9e-01aa6081f461'