apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taraba-nmep-central-prd-appset-health
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: transformer

  template:
    metadata:
      name: 'taraba-{{name}}'

    spec:
      project: taraba-project

      source:
        repoURL: git@github.com:HCM-NIGERIA-NMEP/nmep-devops.git
        targetRevision: nmep-central-prd
        path: config-as-code/helm/charts/health-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../../environments/taraba-nmep-central-prd.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '*'

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s