{{- with index .Values "cluster-configs" "secrets" "egov-notification-push" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
stringData:
  fcm-service-account-key-json: {{ index . "fcm-service-account-key-json" }}
{{- end }}
