{{- with index .Values "cluster-configs" "secrets" "egov-enc-service" }}
{{- if index . "master-password" }}
{{- range $ns := .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "egov-enc-service" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  {{- if index $.Values "cluster-configs" "secrets" "egov-enc-service" "master-password" }}
  master.password: {{ index $.Values "cluster-configs" "secrets" "egov-enc-service" "master-password" | b64enc | quote }}
  master.salt: {{ index $.Values "cluster-configs" "secrets" "egov-enc-service" "master-salt" | b64enc | quote }}
  master.initialvector: {{ index $.Values "cluster-configs" "secrets" "egov-enc-service" "master-initialvector" | b64enc | quote }}
  {{- end }}

  {{- if index $.Values "cluster-configs" "secrets" "egov-enc-service" "aws-kms-access-key" }}
  aws-kms-access-key : {{ index $.Values "cluster-configs" "secrets" "egov-enc-service" "aws-kms-access-key" | b64enc | quote }}
  aws-kms-secret-key: {{ index $.Values "cluster-configs" "secrets" "egov-enc-service" "aws-kms-secret-key" | b64enc | quote }}
  {{- end}}
{{- end }}
---
{{- end }}
{{- end }}