{{- with index .Values "cluster-configs" "secrets" "elastic" }}
{{- if index . "username" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "elastic" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "elastic" "username"  | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "elastic" "password"  | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}