# Common Labels
labels:
  app: "mailbot-cron"
  group: "mailbot-cron"

cron:
  schedule: "*/5 * * * *"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

extraVolumes: |
  - name: tmp
    emptyDir: {}

extraVolumeMounts: |
  - name: tmp
    mountPath: /tmp

# Container Configs
image:
  repository: "byrnedo/alpine-curl"
  tag: "latest"
args: 
- http://mailbot.egov:8080/mailbot/_process
