apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: central-uat-dev-appset-health
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: transformer
          - name: excel-ingestion
          - name: project-factory
          - name: auth-proxy
          - name: census-service
          - name: health-expense-calculator
          - name: plan-service
          - name: resource-generator

  template:
    metadata:
      name: 'dev-{{name}}'

    spec:
      project: dev-project

      source:
        repoURL: git@github.com:HCM-KEBBI/kebbi-devops.git
        targetRevision: central-uat-build
        path: config-as-code/helm/charts/health-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../../environments/dev-central-uat.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '*'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 100
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
