apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: osun-project
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:HCM-KEBBI/kebbi-devops.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc