environments:
  env:
    values:
      - namespace: monitoring
      - ../../environments/ng-upgrade-uat.yaml
    secrets:
      - ../../environments/ng-upgrade-uat-secrets-kebbi-aws-account-alertmanager.yaml
---

repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts

releases:


- name: kube-prometheus-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: prometheus-community/kube-prometheus-stack
  version: 56.6.2
  disableValidation: true
  values:
  - ./values/prometheus.yaml
  - alertmanager:
      enabled: {{ .Values.prometheus.alertmanager.enabled }}
  {{- if .Values.prometheus.alertmanager.enabled }}
  - alertmanager:
      config: {{ index .Values "cluster-configs" "secrets" "alertmanager" "config" | toYaml | nindent 8 }}
  {{- end }}
  - prometheus:
      prometheusSpec:
        additionalScrapeConfigs: {{ .Values.prometheus.additionalScrapeConfigs | toYaml | nindent 8 }}
        externalLabels: {{ .Values.prometheus.externalLabels | toYaml | nindent 10 }}
        storageSpec: {{ .Values.prometheus.storageSpec | toYaml | nindent 10 }}
        retention:  {{ .Values.prometheus.retention | toYaml | nindent 10 }}

- name: jaeger
  installed: false
  namespace: monitoring
  chart: jaegertracing/jaeger
  version: 0.35.0
  values:
  - ./values/jaeger.yaml
  set:
  - name: query.ingress.hosts[0]
    value: "{{ .Values.global.domain }}"

- name: grafana
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/grafana
  version: 7.3.0
  values:
  - ./values/grafana.yaml
  set:
  - name: ingress.hosts[0]
    value: "{{ .Values.global.domain }}"
  - name: ingress.tls[0].hosts[0]
    value: "{{ .Values.global.domain }}"
  - name: ingress.tls[0].secretName
    value: "{{ .Values.global.domain }}-tls-certs"

- name: blackbox
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: ../backbone-services/prometheus-blackbox-exporter
  version: 8.2.0

- name: prometheus-redis-exporter
  installed: false
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: ../backbone-services/prometheus-redis-exporter