apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kebbi-hcm-uat.digit.org-tls-certs
  namespace: egov
spec:
  secretName: kebbi-hcm-uat.digit.org-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kebbi-hcm-uat.digit.org
  dnsNames:
  - kebbi-hcm-uat.digit.org
